[2025-05-05T12:36:33.145+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-05T12:36:33.161+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_resultats_csv.load_csv_jo manual__2025-05-05T12:36:28.690055+00:00 [queued]>
[2025-05-05T12:36:33.168+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_resultats_csv.load_csv_jo manual__2025-05-05T12:36:28.690055+00:00 [queued]>
[2025-05-05T12:36:33.168+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-05-05T12:36:33.179+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_csv_jo> on 2025-05-05 12:36:28.690055+00:00
[2025-05-05T12:36:33.187+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=141) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-05T12:36:33.189+0000] {standard_task_runner.py:72} INFO - Started process 143 to run task
[2025-05-05T12:36:33.190+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ingest_resultats_csv', 'load_csv_jo', 'manual__2025-05-05T12:36:28.690055+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/ingest_resultats_csv.py', '--cfg-path', '/tmp/tmpfknkkl4v']
[2025-05-05T12:36:33.191+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask load_csv_jo
[2025-05-05T12:36:33.236+0000] {task_command.py:467} INFO - Running <TaskInstance: ingest_resultats_csv.load_csv_jo manual__2025-05-05T12:36:28.690055+00:00 [running]> on host 22079d7a1e21
[2025-05-05T12:36:33.308+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_resultats_csv' AIRFLOW_CTX_TASK_ID='load_csv_jo' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T12:36:28.690055+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T12:36:28.690055+00:00'
[2025-05-05T12:36:33.309+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-05T12:36:33.309+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-05T12:36:33.310+0000] {logging_mixin.py:190} INFO - Current task name:load_csv_jo state:running start_date:2025-05-05 12:36:33.162194+00:00
[2025-05-05T12:36:33.310+0000] {logging_mixin.py:190} INFO - Dag name:ingest_resultats_csv and current dag run status:running
[2025-05-05T12:36:33.310+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-05T12:36:34.042+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-05-05T12:36:34.103+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingest_resultats_csv.py", line 100, in load_csv_data
    cursor.execute("""
psycopg2.errors.DatetimeFieldOverflow: date/time field value out of range: "20/02/2022"
LINE 2: ...lympic Games', 2, 'JO Hiver', 2022, '03/02/2022', '20/02/202...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.

[2025-05-05T12:36:34.117+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-05T12:36:34.118+0000] {logging_mixin.py:190} INFO - Task start:2025-05-05 12:36:33.162194+00:00 end:2025-05-05 12:36:34.117203+00:00 duration:0.955009
[2025-05-05T12:36:34.118+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_csv_jo> dag:<DAG: ingest_resultats_csv> dagrun:<DagRun ingest_resultats_csv @ 2025-05-05 12:36:28.690055+00:00: manual__2025-05-05T12:36:28.690055+00:00, state:running, queued_at: 2025-05-05 12:36:28.698775+00:00. externally triggered: True>
[2025-05-05T12:36:34.118+0000] {logging_mixin.py:190} INFO - Failure caused by date/time field value out of range: "20/02/2022"
LINE 2: ...lympic Games', 2, 'JO Hiver', 2022, '03/02/2022', '20/02/202...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.
[2025-05-05T12:36:34.118+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ingest_resultats_csv, task_id=load_csv_jo, run_id=manual__2025-05-05T12:36:28.690055+00:00, execution_date=20250505T123628, start_date=20250505T123633, end_date=20250505T123634
[2025-05-05T12:36:34.131+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-05T12:36:34.132+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 27 for task load_csv_jo (date/time field value out of range: "20/02/2022"
LINE 2: ...lympic Games', 2, 'JO Hiver', 2022, '03/02/2022', '20/02/202...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.
; 143)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingest_resultats_csv.py", line 100, in load_csv_data
    cursor.execute("""
psycopg2.errors.DatetimeFieldOverflow: date/time field value out of range: "20/02/2022"
LINE 2: ...lympic Games', 2, 'JO Hiver', 2022, '03/02/2022', '20/02/202...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.

[2025-05-05T12:36:34.155+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-05T12:36:34.171+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-05T12:36:34.174+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
